#!/bin/sh
echo "This build requires that WiringPi is installed on the RPi"
echo "Please see Chapter 6 on how to install the latest version"
g++ buttonLED.cpp -o buttonLED -lwiringPi
g++ buttonLEDdebounce.cpp -o buttonLEDdb -lwiringPi
g++ fasttoggle.cpp -o fasttoggle -lwiringPi
g++ info.cpp -o info -lwiringPi

